### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [plista/gtm-conversion-plus-event#1]
https://github.com/plista/gtm-conversion-plus-event/blob/c131b043f70fead14c6bec6dbd2d4ea258a8af07/template.tpl#LL60C58-L60C71

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by uberstumbler** [comment]
Fixed. Thank you for raising the issue.
